---
kind: pipeline
name: linux-amd64

steps:
- name: update-success
  image: cloudposse/github-status-updater
  environment:
    GITHUB_TOKEN:
      from_secret: token
    GITHUB_ACTION: update_state
    GITHUB_OWNER: JieJhih
    GITHUB_REPO: cicd
    GITHUB_REF: ${DRONE_COMMIT_SHA}
    GITHUB_CONTEXT: Staging Environment
    GITHUB_STATE: success
    GITHUB_DESCRIPTION: ${CI_JOB_STATUS}
    GITHUB_TARGET_URL: ${DRONE_BUILD_LINK}
  when:
    event:
    - push
    - tag
    status:
    - success

- name: test
  image: golang:1.11
  commands:
  - go test -v ./...