workspace:
  base: /go
  path: src/graduate-project

clone:
  git:
    image: plugins/git
    depth: 1
    tags: false

pipeline:
  commit-status-pend:
    image: gboo/github-status
    from_secret: token
    state: pending
    context: drone

  test:
    image: golang
    commands:
      - go test

  commit-status-failed:
    image: gboo/github-status
    from_secret: token
    state: failure
    context: drone
    when:
      status: [ failure ]

  commit-status-succeed:
    image: gboo/github-status
    from_secret: token
    state: success
    context: drone
    when:
      status: [ success ]