workspace:
  base: /go
  path: src/graduate-project

clone:
  git:
    image: plugins/git
    depth: 1
    tags: false

pipeline:
  commit-status-pend:
    image: jmccann/drone-github-status:rc
    secrets: [ api_token ]
    state: pending
    context: drone

  test:
    image: golang
    commands:
      - go test
      - echo 1

  commit-status-failed:
    image: jmccann/drone-github-status:rc
    secrets: [ api_token ]
    state: failure
    context: drone
    when:
      status: [ failure ]

  commit-status-succeed:
    image: jmccann/drone-github-status:rc
    secrets: [ api_token ]
    state: success
    context: drone
    when:
      status: [ success ]