workspace:
  base: /go
  path: src/graduate-project

clone:
  git:
    image: plugins/git
    depth: 1
    tags: false

pipeline:
  commit-status-pend:
  test:
    image: golang
    commands:
      - env