workspace:
  base: /go
  path: src/graduate-project

clone:
  git:
    image: plugins/git
    depth: 1
    tags: false

pipeline:
  test:
    image: golang
    commands:
      - env

  set-deployment-status-to-success:
    image: cloudposse/github-status-updater
    secrets:
      - source: token
        target: GITHUB_TOKEN
    environment:
      - GITHUB_ACTION=update_state
      - GITHUB_OWNER=JieJhih
      - GITHUB_REPO=cicd
      - GITHUB_REF=${DRONE_COMMIT_SHA}
      - GITHUB_CONTEXT=Staging Environment
      - GITHUB_STATE=success
      - GITHUB_DESCRIPTION=Deployed to namespace
      - GITHUB_TARGET_URL=http://master.demo.cloudposse.org